import {
  createEffect,
  createMemo,
  createSignal,
  For,
  Match,
  on,
  onCleanup,
  onMount,
  Show,
  Switch,
} from "solid-js";
import Footer from "../components/Footer";
import Icon from "../components/Icon";
import Nav from "../components/Nav";
import { guides, type Guide, type GuideBlock } from "../data/docs/guides";
import {
  hashToRoute,
  highlightParts,
  queryWords,
  routeToHash,
  search,
  snippet,
  type Route,
  type SearchResult,
} from "../data/docs/search";
import {
  ancestors,
  childPages,
  rootPage,
  settingCount,
  settings,
  settingsPages,
  type SettingItem,
  type SettingsPage,
} from "../data/docs/settings";
import { links } from "../data/links";

const guidesById = new Map(guides.map((guide) => [guide.id, guide]));

const linkClass = "text-leaf hover:text-leaf-bright";

function Highlighted(props: { text: string; words: string[] }) {
  return (
    <For each={highlightParts(props.text, props.words)}>
      {(part) =>
        part.hit ? (
          <mark class="rounded-sm bg-amber-bg text-amber-ink">{part.text}</mark>
        ) : (
          part.text
        )
      }
    </For>
  );
}

function Paragraphs(props: { text: string; class?: string }) {
  return (
    <For each={props.text.split(/\n{2,}/)}>
      {(paragraph) => <p class={`whitespace-pre-line ${props.class ?? ""}`}>{paragraph}</p>}
    </For>
  );
}

function AiNotice(props: { compact?: boolean }) {
  return (
    <div
      role="note"
      class={`flex items-start gap-3 rounded-2xl border-[1.5px] border-amber-line bg-amber-bg text-amber-ink ${
        props.compact ? "px-4 py-3 text-[15px]" : "px-5 py-4"
      }`}
    >
      <Icon name="warning" class="mt-0.5 size-5 shrink-0" />
      <p>
        <span class="font-bold">This documentation is generated by AI and may not be correct.</span>{" "}
        It was produced automatically from the Moblin source code and has not been reviewed by a
        human. When in doubt, trust the app and ask on{" "}
        <a href={links.discord} target="_blank" rel="noopener" class="font-bold underline">
          Discord
        </a>
        .
      </p>
    </div>
  );
}

function SearchBox(props: {
  query: string;
  onInput: (query: string) => void;
  ref: (element: HTMLInputElement) => void;
}) {
  return (
    <label class="relative flex w-full items-center">
      <span class="sr-only">Search the documentation</span>
      <svg
        viewBox="0 0 24 24"
        class="pointer-events-none absolute left-4 size-5 text-muted"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        aria-hidden="true"
      >
        <circle cx="11" cy="11" r="7" />
        <path d="m20 20-3.5-3.5" />
      </svg>
      <input
        ref={props.ref}
        type="text"
        enterkeyhint="search"
        value={props.query}
        onInput={(event) => props.onInput(event.currentTarget.value)}
        placeholder="Search settings and guides"
        autocomplete="off"
        spellcheck={false}
        class="h-14 w-full rounded-2xl border-[1.5px] border-line bg-card pr-14 pl-12 text-[17px] text-ink placeholder:text-muted focus:border-leaf focus:outline-none"
      />
      <Show
        when={props.query}
        fallback={
          <kbd class="pointer-events-none absolute right-4 hidden rounded-md border border-line px-2 py-0.5 font-mono text-sm text-muted sm:block">
            /
          </kbd>
        }
      >
        <button
          type="button"
          class="absolute right-2 flex size-10 items-center justify-center rounded-xl text-muted hover:bg-ghost hover:text-ink"
          aria-label="Clear search"
          onClick={() => props.onInput("")}
        >
          <Icon name="close" class="size-5" />
        </button>
      </Show>
    </label>
  );
}

function TreeNode(props: { page: SettingsPage; current?: SettingsPage }) {
  const children = createMemo(() => childPages(props.page));
  const isCurrent = () => props.current?.id === props.page.id;
  const containsCurrent = () =>
    props.current !== undefined &&
    ancestors(props.current).some((ancestor) => ancestor.id === props.page.id);
  const [open, setOpen] = createSignal(false);
  createEffect(() => {
    if (containsCurrent()) {
      setOpen(true);
    }
  });
  return (
    <li>
      <div class="flex items-center">
        <Show
          when={children().length > 0}
          fallback={<span class="size-7 shrink-0" aria-hidden="true" />}
        >
          <button
            type="button"
            class="flex size-7 shrink-0 items-center justify-center rounded-md text-muted hover:bg-ghost hover:text-ink"
            aria-label={`${open() ? "Collapse" : "Expand"} ${props.page.title}`}
            aria-expanded={open()}
            onClick={() => setOpen(!open())}
          >
            <svg
              viewBox="0 0 24 24"
              class={`size-4 transition-transform ${open() ? "rotate-90" : ""}`}
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="m9 6 6 6-6 6" />
            </svg>
          </button>
        </Show>
        <a
          href={routeToHash({ kind: "settings", id: props.page.id })}
          class={`min-w-0 flex-1 truncate rounded-lg px-2 py-1 text-[15px] ${
            isCurrent()
              ? "bg-ghost font-bold text-leaf"
              : "text-ink-2 hover:bg-ghost hover:text-ink"
          }`}
          aria-current={isCurrent() ? "page" : undefined}
          title={props.page.title}
        >
          {props.page.title}
        </a>
      </div>
      <Show when={open() && children().length > 0}>
        <ul class="ml-3.5 border-l border-line pl-1">
          <For each={children()}>
            {(child) => <TreeNode page={child} current={props.current} />}
          </For>
        </ul>
      </Show>
    </li>
  );
}

function Sidebar(props: { route: Route }) {
  const currentPage = () =>
    props.route.kind === "settings" ? settingsPages.get(props.route.id) : undefined;
  const currentGuide = () => (props.route.kind === "guide" ? props.route.id : undefined);
  return (
    <nav aria-label="Documentation" class="flex flex-col gap-6">
      <div class="flex flex-col gap-1">
        <a
          href="#"
          class={`rounded-lg px-2 py-1 font-display text-[15px] font-semibold uppercase tracking-[0.08em] ${
            props.route.kind === "home" ? "text-leaf" : "text-muted hover:text-ink"
          }`}
        >
          Overview
        </a>
      </div>
      <div class="flex flex-col gap-1">
        <h2 class="px-2 font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-muted">
          Guides
        </h2>
        <ul class="flex flex-col">
          <For each={guides}>
            {(guide) => (
              <li>
                <a
                  href={routeToHash({ kind: "guide", id: guide.id })}
                  class={`block truncate rounded-lg px-2 py-1 text-[15px] ${
                    currentGuide() === guide.id
                      ? "bg-ghost font-bold text-leaf"
                      : "text-ink-2 hover:bg-ghost hover:text-ink"
                  }`}
                  aria-current={currentGuide() === guide.id ? "page" : undefined}
                  title={guide.title}
                >
                  {guide.title}
                </a>
              </li>
            )}
          </For>
        </ul>
      </div>
      <div class="flex flex-col gap-1">
        <h2 class="px-2 font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-muted">
          Settings
        </h2>
        <ul class="flex flex-col">
          <For each={childPages(rootPage)}>
            {(page) => <TreeNode page={page} current={currentPage()} />}
          </For>
        </ul>
      </div>
    </nav>
  );
}

function Breadcrumbs(props: { page: SettingsPage }) {
  return (
    <ol class="flex flex-wrap items-center gap-x-1.5 gap-y-1 text-[15px] text-muted">
      <For each={ancestors(props.page)}>
        {(ancestor) => (
          <li class="flex items-center gap-1.5">
            <a href={routeToHash({ kind: "settings", id: ancestor.id })} class="hover:text-ink">
              {ancestor.title}
            </a>
            <span aria-hidden="true">›</span>
          </li>
        )}
      </For>
      <li class="text-ink-2" aria-current="page">
        {props.page.title}
      </li>
    </ol>
  );
}

const typeLabels: Record<SettingItem["type"], string> = {
  toggle: "Toggle",
  picker: "Choice",
  setting: "Value",
  page: "Page",
  note: "Note",
};

function ItemRow(props: { item: SettingItem; id: string }) {
  return (
    <Switch>
      <Match when={props.item.type === "note"}>
        <li id={props.id} class="docs-target flex gap-3 px-5 py-3 text-ink-2 sm:px-6">
          <Paragraphs text={props.item.label} class="text-[15px]" />
        </li>
      </Match>
      <Match when={props.item.page && settingsPages.has(props.item.page)}>
        <li id={props.id} class="docs-target">
          <a
            href={routeToHash({ kind: "settings", id: props.item.page! })}
            class="group flex items-start justify-between gap-4 px-5 py-3.5 hover:bg-ghost sm:px-6"
          >
            <span class="flex flex-col gap-1">
              <span class="font-bold text-ink group-hover:text-leaf">{props.item.label}</span>
              <Show when={props.item.description}>
                <span class="text-[15px] text-ink-2">{props.item.description}</span>
              </Show>
            </span>
            <svg
              viewBox="0 0 24 24"
              class="mt-1 size-5 shrink-0 text-muted group-hover:text-leaf"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="m9 6 6 6-6 6" />
            </svg>
          </a>
        </li>
      </Match>
      <Match when={true}>
        <li id={props.id} class="docs-target flex flex-col gap-2 px-5 py-3.5 sm:px-6">
          <div class="flex flex-wrap items-center justify-between gap-x-4 gap-y-1">
            <span class="font-bold text-ink">{props.item.label}</span>
            <span class="flex items-center gap-2 text-sm">
              <Show when={props.item.default}>
                <span class="text-muted">
                  Default <span class="font-bold text-ink-2">{props.item.default}</span>
                </span>
              </Show>
              <span class="rounded-full border border-line px-2 py-0.5 text-[13px] font-semibold text-muted">
                {typeLabels[props.item.type]}
              </span>
            </span>
          </div>
          <Show when={props.item.description}>
            <div class="flex flex-col gap-2 text-[15px] text-ink-2">
              <Paragraphs text={props.item.description!} />
            </div>
          </Show>
          <Show when={props.item.options}>
            <ul class="flex flex-wrap gap-1.5" aria-label="Options">
              <For each={props.item.options}>
                {(option) => (
                  <li class="rounded-lg bg-well px-2 py-0.5 text-sm text-ink-2">{option}</li>
                )}
              </For>
            </ul>
          </Show>
        </li>
      </Match>
    </Switch>
  );
}

function SettingsPageView(props: { page: SettingsPage }) {
  const sourceUrl = `${links.github}/tree/${settings.commit}/Moblin/View/Settings`;
  return (
    <article class="flex flex-col gap-6">
      <header class="flex flex-col gap-3">
        <Breadcrumbs page={props.page} />
        <h1 class="text-[34px] leading-tight font-bold sm:text-[44px]">{props.page.title}</h1>
        <AiNotice compact />
      </header>
      <Show
        when={props.page.sections.length > 0}
        fallback={<p class="text-ink-2">This page has no settings of its own.</p>}
      >
        <For each={props.page.sections}>
          {(section, sectionIndex) => (
            <section class="flex flex-col gap-2">
              <Show when={section.header}>
                <h2 class="px-1 font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-muted">
                  {section.header}
                </h2>
              </Show>
              <Show when={section.items.length > 0}>
                <ul class="divide-y divide-line overflow-hidden rounded-2xl border-[1.5px] border-line bg-card">
                  <For each={section.items}>
                    {(item, itemIndex) => (
                      <ItemRow item={item} id={`item-${sectionIndex()}-${itemIndex()}`} />
                    )}
                  </For>
                </ul>
              </Show>
              <Show when={section.footer}>
                <div class="flex flex-col gap-2 px-1 text-[15px] text-muted">
                  <Paragraphs text={section.footer!} />
                </div>
              </Show>
            </section>
          )}
        </For>
      </Show>
      <p class="text-sm text-muted">
        Generated by AI from the{" "}
        <a href={sourceUrl} target="_blank" rel="noopener" class={linkClass}>
          Moblin source code
        </a>{" "}
        of {settings.date}. Some settings only show up for certain devices, streams or when Show all
        settings is on.
      </p>
    </article>
  );
}

function Block(props: { block: GuideBlock; id: string }) {
  const block = props.block;
  switch (block.type) {
    case "h":
      return (
        <h2 id={props.id} class="docs-target mt-4 text-[26px] font-semibold">
          {block.text}
        </h2>
      );
    case "p":
      return (
        <p id={props.id} class="docs-target text-ink-2">
          {block.text}
        </p>
      );
    case "tip":
      return (
        <p
          id={props.id}
          class="docs-target rounded-2xl border-[1.5px] border-amber-line bg-amber-bg px-5 py-4 text-amber-ink"
        >
          {block.text}
        </p>
      );
    case "steps":
      return (
        <ol id={props.id} class="docs-target flex flex-col gap-3">
          <For each={block.items}>
            {(item, index) => (
              <li class="flex gap-3">
                <span class="flex size-7 shrink-0 items-center justify-center rounded-full bg-moss font-display text-[15px] font-semibold text-white">
                  {index() + 1}
                </span>
                <span class="pt-0.5 text-ink-2">{item}</span>
              </li>
            )}
          </For>
        </ol>
      );
    case "list":
      return (
        <ul id={props.id} class="docs-target flex list-disc flex-col gap-2 pl-6 text-ink-2">
          <For each={block.items}>{(item) => <li>{item}</li>}</For>
        </ul>
      );
  }
}

function GuideView(props: { guide: Guide }) {
  const related = () =>
    props.guide.related.flatMap((id) => {
      const page = settingsPages.get(id);
      return page ? [page] : [];
    });
  const position = () => guides.indexOf(props.guide);
  const next = () => guides[position() + 1];
  return (
    <article class="flex max-w-[720px] flex-col gap-5">
      <header class="flex flex-col gap-3">
        <span class="font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-leaf">
          Guide
        </span>
        <h1 class="text-[34px] leading-tight font-bold sm:text-[44px]">{props.guide.title}</h1>
        <p class="text-lg text-ink-2 sm:text-[19px]">{props.guide.summary}</p>
        <AiNotice compact />
      </header>
      <For each={props.guide.blocks}>
        {(block, index) => <Block block={block} id={`block-${index()}`} />}
      </For>
      <Show when={related().length > 0}>
        <section class="mt-4 flex flex-col gap-3">
          <h2 class="font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-muted">
            Related settings
          </h2>
          <ul class="flex flex-wrap gap-2">
            <For each={related()}>
              {(page) => (
                <li>
                  <a
                    href={routeToHash({ kind: "settings", id: page.id })}
                    class="flex flex-col rounded-xl border-[1.5px] border-line bg-card px-4 py-2 hover:border-leaf"
                  >
                    <span class="font-bold">{page.title}</span>
                    <span class="text-sm text-muted">{page.path.slice(0, -1).join(" › ")}</span>
                  </a>
                </li>
              )}
            </For>
          </ul>
        </section>
      </Show>
      <Show when={next()}>
        {(guide) => (
          <a
            href={routeToHash({ kind: "guide", id: guide().id })}
            class="mt-4 flex flex-col gap-1 self-end rounded-2xl border-[1.5px] border-line bg-card px-5 py-4 text-right hover:border-leaf"
          >
            <span class="text-sm text-muted">Next guide</span>
            <span class="font-bold text-leaf">{guide().title} →</span>
          </a>
        )}
      </Show>
    </article>
  );
}

function Overview() {
  const categories = childPages(rootPage);
  return (
    <div class="flex flex-col gap-12">
      <section class="flex flex-col gap-5">
        <h2 class="text-[28px] font-semibold">Guides</h2>
        <ul class="grid gap-4 sm:grid-cols-2">
          <For each={guides}>
            {(guide) => (
              <li>
                <a
                  href={routeToHash({ kind: "guide", id: guide.id })}
                  class="flex h-full flex-col gap-1.5 rounded-2xl border-[1.5px] border-line bg-card p-5 hover:border-leaf"
                >
                  <span class="font-display text-[19px] font-semibold">{guide.title}</span>
                  <span class="text-[15px] text-ink-2">{guide.summary}</span>
                </a>
              </li>
            )}
          </For>
        </ul>
      </section>
      <section class="flex flex-col gap-5">
        <div class="flex flex-col gap-2">
          <h2 class="text-[28px] font-semibold">All settings</h2>
          <p class="text-ink-2">
            Every page under Settings in the app, with what each option does. Some pages only show
            up when Show all settings at the bottom of Settings is on.
          </p>
        </div>
        <ul class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <For each={categories}>
            {(page) => (
              <li>
                <a
                  href={routeToHash({ kind: "settings", id: page.id })}
                  class="flex h-full items-center justify-between gap-3 rounded-2xl border-[1.5px] border-line bg-card px-5 py-4 hover:border-leaf"
                >
                  <span class="font-bold">{page.title}</span>
                  <span class="text-sm text-muted">{settingCount(page)}</span>
                </a>
              </li>
            )}
          </For>
        </ul>
        <Show when={rootPage.sections.some((section) => section.items.some((i) => !i.page))}>
          <ul class="divide-y divide-line overflow-hidden rounded-2xl border-[1.5px] border-line bg-card">
            <For each={rootPage.sections}>
              {(section, sectionIndex) => (
                <For each={section.items}>
                  {(item, itemIndex) => (
                    <Show when={!item.page}>
                      <ItemRow item={item} id={`item-${sectionIndex()}-${itemIndex()}`} />
                    </Show>
                  )}
                </For>
              )}
            </For>
          </ul>
        </Show>
      </section>
    </div>
  );
}

const kindLabels: Record<SearchResult["entry"]["kind"], string> = {
  guide: "Guide",
  page: "Page",
  setting: "Setting",
};

function SearchResults(props: { query: string }) {
  const words = createMemo(() => queryWords(props.query));
  const results = createMemo(() => search(props.query));
  return (
    <section class="flex flex-col gap-4" aria-live="polite">
      <h1 class="text-[28px] font-semibold">
        <Show when={results().length > 0} fallback={<>No results for “{props.query}”</>}>
          Results for “{props.query}”
        </Show>
      </h1>
      <Show when={results().length === 0}>
        <p class="text-ink-2">
          Try fewer or other words, or ask on{" "}
          <a href={links.discord} target="_blank" rel="noopener" class={linkClass}>
            Discord
          </a>
          .
        </p>
      </Show>
      <ul class="flex flex-col gap-2">
        <For each={results()}>
          {(result) => (
            <li>
              <a
                href={routeToHash(result.entry.route)}
                onClick={() => history.replaceState({ scroll: window.scrollY }, "")}
                class="flex flex-col gap-1 rounded-2xl border-[1.5px] border-line bg-card px-5 py-3.5 hover:border-leaf"
              >
                <span class="flex flex-wrap items-center gap-x-3 gap-y-1">
                  <span class="font-bold text-ink">
                    <Highlighted text={result.entry.title} words={words()} />
                  </span>
                  <span class="rounded-full border border-line px-2 py-0.5 text-[13px] font-semibold text-muted">
                    {kindLabels[result.entry.kind]}
                  </span>
                </span>
                <Show when={result.entry.path.length > 0}>
                  <span class="text-sm text-muted">{result.entry.path.join(" › ")}</span>
                </Show>
                <Show when={result.entry.text}>
                  <span class="text-[15px] text-ink-2">
                    <Highlighted text={snippet(result.entry.text, words())} words={words()} />
                  </span>
                </Show>
              </a>
            </li>
          )}
        </For>
      </ul>
    </section>
  );
}

function NotFound() {
  return (
    <div class="flex flex-col gap-3">
      <h1 class="text-[34px] font-bold">Page not found</h1>
      <p class="text-ink-2">
        It may have moved in a newer version of Moblin.{" "}
        <a href="#" class={linkClass}>
          Back to the overview
        </a>
        .
      </p>
    </div>
  );
}

export default function Docs() {
  const [route, setRoute] = createSignal<Route>(hashToRoute(location.hash));
  const [menuOpen, setMenuOpen] = createSignal(false);
  let input: HTMLInputElement | undefined;
  let main: HTMLDivElement | undefined;

  const query = () => {
    const current = route();
    return current.kind === "search" ? current.query : "";
  };
  const setQuery = (text: string) => {
    const searching = route().kind === "search";
    const next: Route = text ? { kind: "search", query: text } : { kind: "home" };
    const url = text ? routeToHash(next) : location.pathname;
    if (searching) {
      history.replaceState(null, "", url);
    } else if (text) {
      history.pushState(null, "", url);
    } else {
      return;
    }
    setRoute(next);
  };
  const onHashChange = () => {
    setRoute(hashToRoute(location.hash));
    setMenuOpen(false);
  };
  const onKeyDown = (event: KeyboardEvent) => {
    const target = event.target as HTMLElement;
    const typing = target.closest("input, textarea, [contenteditable]") !== null;
    if (event.key === "/" && !typing) {
      event.preventDefault();
      input?.focus();
    } else if (event.key === "Escape" && target === input) {
      setQuery("");
    }
  };
  onMount(() => {
    window.addEventListener("hashchange", onHashChange);
    window.addEventListener("keydown", onKeyDown);
  });
  onCleanup(() => {
    window.removeEventListener("hashchange", onHashChange);
    window.removeEventListener("keydown", onKeyDown);
  });

  const title = () => {
    const current = route();
    if (current.kind === "guide") {
      return guidesById.get(current.id)?.title;
    }
    if (current.kind === "settings") {
      return settingsPages.get(current.id)?.path.join(" › ");
    }
    if (current.kind === "search") {
      return `Search for “${current.query}”`;
    }
    return undefined;
  };

  createEffect(() => {
    document.title = title() ? `${title()} – Moblin docs` : "Documentation – Moblin";
  });

  createEffect(
    on(route, (current) => {
      requestAnimationFrame(() => {
        if (current.kind === "search") {
          const scroll = (history.state as { scroll?: number } | null)?.scroll;
          if (scroll !== undefined) {
            window.scrollTo(0, scroll);
          }
          return;
        }
        const anchor = current.kind === "home" ? undefined : current.anchor;
        const element = anchor ? document.getElementById(anchor) : null;
        if (element) {
          element.scrollIntoView({ block: "center" });
          element.classList.remove("docs-flash");
          void element.offsetWidth;
          element.classList.add("docs-flash");
        } else if (main && main.getBoundingClientRect().top < 0) {
          main.scrollIntoView();
        }
      });
    }),
  );

  return (
    <>
      <Nav />
      <main>
        <section class="border-b border-line/40 bg-band">
          <div class="mx-auto flex max-w-[1120px] flex-col gap-5 px-5 pt-10 pb-8 sm:px-8 lg:pt-14">
            <div class="flex flex-col gap-2">
              <span class="font-display text-[15px] font-semibold uppercase tracking-[0.08em] text-leaf">
                Documentation
              </span>
              <h1 class="text-[36px] leading-[1.05] font-bold text-balance sm:text-5xl">
                How to use Moblin
              </h1>
              <p class="max-w-[640px] text-lg text-ink-2 text-pretty">
                Step-by-step guides and every setting in the app, searchable in one place.
              </p>
            </div>
            <AiNotice />
            <SearchBox query={query()} onInput={setQuery} ref={(element) => (input = element)} />
          </div>
        </section>
        <div
          ref={(element) => (main = element)}
          class="mx-auto max-w-[1120px] scroll-mt-16 px-5 py-8 sm:px-8 lg:grid lg:scroll-mt-18 lg:grid-cols-[250px_minmax(0,1fr)] lg:gap-10 lg:py-12"
        >
          <div class="mb-6 lg:hidden">
            <button
              type="button"
              class="flex w-full items-center justify-between rounded-2xl border-[1.5px] border-line bg-card px-5 py-3 font-bold"
              aria-expanded={menuOpen()}
              onClick={() => setMenuOpen(!menuOpen())}
            >
              Browse guides and settings
              <Icon name={menuOpen() ? "close" : "menu"} class="size-5" />
            </button>
            <Show when={menuOpen()}>
              <div class="mt-3 rounded-2xl border-[1.5px] border-line bg-card p-3">
                <Sidebar route={route()} />
              </div>
            </Show>
          </div>
          <aside class="hidden lg:block">
            <div class="sticky top-[calc(4.5rem+24px)] max-h-[calc(100vh-4.5rem-48px)] overflow-y-auto pr-2 pb-8">
              <Sidebar route={route()} />
            </div>
          </aside>
          <div class="min-w-0">
            <Show when={!query()} fallback={<SearchResults query={query()} />}>
              <Switch fallback={<NotFound />}>
                <Match when={route().kind === "home"}>
                  <Overview />
                </Match>
                <Match
                  when={(() => {
                    const current = route();
                    return current.kind === "guide" ? guidesById.get(current.id) : undefined;
                  })()}
                >
                  {(guide) => <GuideView guide={guide()} />}
                </Match>
                <Match
                  when={(() => {
                    const current = route();
                    return current.kind === "settings" ? settingsPages.get(current.id) : undefined;
                  })()}
                >
                  {(page) => <SettingsPageView page={page()} />}
                </Match>
              </Switch>
            </Show>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
