name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Source code styling
        run: |
          brew install just oxfmt
          just style-check
      - name: Linting
        run: |
          brew install oxlint
          just lint
